---
output: 
  github_document
---


<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "inst/vignette-supp/",
  echo=TRUE, 
  warning=FALSE, 
  message=FALSE,
  tidy=TRUE
)
```

# coher

An R package for the estimation of co-heritability of phenotypic traits in bacteria.

## Installation

The development version is available on github. It can be installed with `devtools`

```{r, eval = FALSE, warning=FALSE}
install.packages("remotes")

remotes::install_github("tienmt/coher")
```

If you would like to also build the vignette with your installation run:

```{r, eval=FALSE}
remotes::install_github("tienmt/coher", build_vignettes = TRUE)
```

## Quick Start

Run coher

```{r, fig.width =8, fig.height=6, fig.align='center'}
# install.packages("coher")
library(coher)

data('coher_example')
result <- coher(coher_example$Y, coher_example$X)
```

```{r, echo = FALSE}
intro_rmd <- 'vignettes/introduction.Rmd'

raw_rmd <- readLines(intro_rmd)

# remove yaml 
yaml_lines <- grep("---", raw_rmd)

# remove appendix (session info)
appendix <- grep("Session", raw_rmd)

compressed_rmd <- raw_rmd[c(-seq(yaml_lines[1], yaml_lines[2], by = 1), 
                            -seq(appendix, length(raw_rmd)))]
writeLines(compressed_rmd, "child.Rmd")
```

```{r, child = 'child.Rmd'}
```

```{r cleanup, echo=FALSE, include=FALSE}
if (file.exists("child.Rmd")) {
  file.remove("child.Rmd")
}
```
